"""Write the generated Markdown from _variables.yml.

Outputs (all overwritten on every run, never edited by hand):
  _includes/facts.md         the counts under the landing page's hero
  _includes/days.md          the four days as cards
  _includes/path.md          the module arc on the landing page
  _includes/schedule.md      the timetable
  _includes/day-N.md         the module cards for one day
  _includes/module-NN.md     the header block of one lecture page
  _includes/notebooks.md     the notebook index with Colab links
  _includes/readiness.md     the readiness page: evidence per module, blocking work
  _includes/readiness-summary.md  the one-paragraph status on the landing, FAQ and teach pages
  _includes/sidebar.yml      the module sidebar, read by _quarto.yml (metadata-files)
  README.md                  the regions between the BEGIN/END status and modules markers

It also creates a stub lecture page for any module that has none. Existing
lecture pages are never touched.

The readiness outputs read modules.mNN.readiness and readiness: in _variables.yml and the
run records in runs/ (scripts/readiness.py). They print dates from the records, never today's
date, so they change only when the repository does.

Module numbers start at 0. A module with `notebook: false` (Module 0) has no
lab: it gets a lecture page and a row in the day, schedule and README tables,
but no row in the notebook index. A day's optional `self_serve` module fills
the schedule's `self_serve` slot.

Run:  uv run --group site python scripts/gen_tables.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
import readiness  # noqa: E402
import run_records  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
INCLUDES = ROOT / "_includes"
NOTICE = "<!-- GENERATED by scripts/gen_tables.py from _variables.yml. Do not edit by hand. -->"
YAML_NOTICE = "# GENERATED by scripts/gen_tables.py from _variables.yml. Do not edit by hand."
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"
NO_NOTEBOOK = "No notebook: runs in your terminal"


def load_variables() -> dict:
    return yaml.safe_load((ROOT / "_variables.yml").read_text(encoding="utf-8"))


def modules_in_order(v: dict) -> list[tuple[str, dict]]:
    return sorted(v["modules"].items(), key=lambda kv: kv[1]["n"])


def days_in_order(v: dict) -> list[dict]:
    return sorted(v["days"].values(), key=lambda d: d["n"])


def notebook_exists(slug: str) -> bool:
    return (ROOT / "notebooks" / f"{slug}.ipynb").exists()


def has_notebook(m: dict) -> bool:
    return m.get("notebook", True)


def colab_badge(v: dict, slug: str) -> str:
    """A Colab badge if the notebook exists, otherwise a plain note."""
    if not notebook_exists(slug):
        return "In preparation"
    return f"[![Open in Colab]({BADGE})]({v['repo']['colab_base']}/{slug}.ipynb)"


def lab_cell(v: dict, m: dict) -> str:
    return colab_badge(v, m["slug"]) if has_notebook(m) else NO_NOTEBOOK


def slot_parts(slot) -> tuple[str, str | None]:
    """A day slot is a module key, or {module, label} to override the label."""
    if isinstance(slot, dict):
        return slot["module"], slot.get("label")
    return slot, None


def day_slots(day: dict) -> list:
    """The day's optional self-serve slot, then its module slots."""
    return ([day["self_serve"]] if day.get("self_serve") else []) + day["slots"]


def self_serve_time(v: dict, key: str) -> str | None:
    """'08:00–09:00' if module `key` fills a day's self-serve slot."""
    keys = {slot_parts(d["self_serve"])[0] for d in v["days"].values() if d.get("self_serve")}
    if key not in keys:
        return None
    slot = next(s for s in v["schedule"]["slots"] if s["kind"] == "self_serve")
    return f"{slot['start']}–{slot['end']}"


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{NOTICE}\n\n{body.rstrip()}\n", encoding="utf-8")


def clock(minutes: int) -> str:
    return f"{minutes // 60:02d}:{minutes % 60:02d}"


def to_minutes(hhmm: str) -> int:
    return int(hhmm[:2]) * 60 + int(hhmm[3:])


def module_clock(v: dict, key: str) -> str:
    """'09:10–10:45': from the start of the module's first slot to the end of its last."""
    own = self_serve_time(v, key)
    if own:
        return own
    day = next(d for d in v["days"].values() if d["n"] == v["modules"][key]["day"])
    slots = [s for s in v["schedule"]["slots"] if s["kind"] == "module"]
    mine = [s for s, d in zip(slots, day["slots"], strict=True) if slot_parts(d)[0] == key]
    return f"{mine[0]['start']}–{mine[-1]['end']}"


def has_split(v: dict, m: dict) -> bool:
    """True for the standard module shape: one lecture, then one lab."""
    w = v["workshop"]
    return m["minutes"] == w["lecture_minutes"] + w["lab_minutes"]


def colab_button(v: dict, m: dict, text: str = "Open in Colab") -> str:
    """A styled link to the lab (site pages only; README keeps the image badge)."""
    if not has_notebook(m):
        return f"[{NO_NOTEBOOK}]{{.lab-note}}"
    if not notebook_exists(m["slug"]):
        return "[Lab in preparation]{.lab-note}"
    return f"[{text}]({v['repo']['colab_base']}/{m['slug']}.ipynb){{.btn-colab}}"


def chips(items: list[str]) -> str:
    return " ".join(f"[{item}]{{.chip}}" for item in items)


def day_modules(v: dict, day: dict) -> list[tuple[str, dict]]:
    """The day's modules in order, each once (the capstone fills two slots)."""
    keys = list(dict.fromkeys(slot_parts(slot)[0] for slot in day_slots(day)))
    return [(key, v["modules"][key]) for key in keys]


def is_optional(v: dict, key: str) -> bool:
    return self_serve_time(v, key) is not None


def facts_strip(v: dict) -> str:
    w = v["workshop"]
    taught = [key for key in v["modules"] if not is_optional(v, key)]
    labs = sum(1 for m in v["modules"].values() if has_notebook(m)) + 1  # plus 00-setup
    facts = [
        f"**{w['days']}** days",
        f"**{len(taught)}** modules",
        f"**{labs}** Colab notebooks",
        f"**{w['lecture_minutes']}** min lecture + **{w['lab_minutes']}** min lab",
    ]
    return "::: {.facts}\n" + "\n".join(f"[{f}]{{.fact}}" for f in facts) + "\n:::"


def days_cards(v: dict) -> str:
    out = ["::: {.day-grid}"]
    for d in days_in_order(v):
        taught = [m["n"] for key, m in day_modules(v, d) if not is_optional(v, key)]
        span = f"Modules {taught[0]}–{taught[-1]}"
        out += [
            "::: {.day-card}",
            f"[Day {d['n']}]{{.eyebrow}}",
            "",
            f"[{d['title']}](day-{d['n']}.qmd){{.day-card-title}}",
            "",
            f"[{d['question']}]{{.day-card-question}}",
            "",
            f"[{span}]{{.day-card-span}}",
            ":::",
        ]
    out.append(":::")
    return "\n".join(out)


def path_steps(v: dict) -> str:
    """The module arc for the landing page: one step per module, grouped by day."""
    out = ["::: {.path}"]
    for d in days_in_order(v):
        out += [
            "::: {.path-day}",
            f"[Day {d['n']} · {d['short']}](day-{d['n']}.qmd){{.path-day-label}}",
            "",
        ]
        for key, m in day_modules(v, d):
            optional = is_optional(v, key)
            tag = " [Optional, self-serve]{.chip}" if optional else ""
            out += [
                "::: {.path-step" + (" .path-step-optional" if optional else "") + "}",
                f"[{m['n']}]{{.path-num}}",
                "",
                "::: {.path-body}",
                f"[{m['title']}](lectures/{m['slug']}.qmd){{.path-title}}{tag}",
                "",
                m["summary"],
                ":::",
                ":::",
            ]
        out.append(":::")
    out.append(":::")
    return "\n".join(out)


def schedule_table(v: dict) -> str:
    """The timetable. Spans carry the classes custom.scss uses to tell lecture, lab,
    break and optional slots apart; the table itself stays a plain pipe table."""
    days = days_in_order(v)
    w = v["workshop"]
    head = "| Time | " + " | ".join(f"[Day {d['n']}](day-{d['n']}.qmd) {d['short']}" for d in days)
    rows = [head + " |", "|---|" + "---|" * len(days)]
    module_index = 0
    for slot in v["schedule"]["slots"]:
        cells = []
        for d in days:
            if slot["kind"] == "opening":
                cells.append(f"[{d['opening']}]{{.slot-opening}}")
            elif slot["kind"] == "self_serve":
                if d.get("self_serve"):
                    key, label = slot_parts(d["self_serve"])
                    m = v["modules"][key]
                    text = label or m["title"]
                    cells.append(f"[{m['n']} · {text}](lectures/{m['slug']}.qmd){{.slot-optional}}")
                else:
                    cells.append("")
            elif slot["kind"] == "break":
                cells.append(f"[{slot['label']}]{{.slot-break}}")
            else:
                key, label = slot_parts(d["slots"][module_index])
                m = v["modules"][key]
                text = label or m["title"]
                cell = f"[{m['n']} · {text}](lectures/{m['slug']}.qmd){{.slot-module}}"
                if has_split(v, m):
                    lab_start = clock(to_minutes(slot["start"]) + w["lecture_minutes"])
                    cell += (
                        f" [[Lecture {slot['start']}]{{.slot-lecture}}"
                        f"[Lab {lab_start}]{{.slot-lab}}]{{.slot-split}}"
                    )
                else:
                    cell += " [[Hands-on]{.slot-lab}]{.slot-split}"
                cells.append(cell)
        if slot["kind"] == "module":
            module_index += 1
        rows.append(f"| {slot['start']}–{slot['end']} | " + " | ".join(cells) + " |")
    return "\n".join(rows)


def timing(v: dict, key: str, m: dict) -> str:
    w = v["workshop"]
    own = self_serve_time(v, key)
    if own:
        return f"{m['minutes']} minutes, self-serve, {own}"
    if has_split(v, m):
        return f"{m['minutes']} minutes ({w['lecture_minutes']} lecture, {w['lab_minutes']} lab)"
    return f"{m['minutes']} minutes"


def day_cards(v: dict, day: dict) -> str:
    """One card per module of the day, with its clock time."""
    out = ["::: {.module-cards}"]
    for key, m in day_modules(v, day):
        optional = is_optional(v, key)
        label = f"Module {m['n']}" + (" · optional, self-serve" if optional else "")
        out += [
            "::: {.module-card" + (" .module-card-optional" if optional else "") + "}",
            "::: {.module-card-time}",
            module_clock(v, key),
            ":::",
            "",
            "::: {.module-card-body}",
            f"[{label}]{{.eyebrow}}",
            "",
            f"[{m['title']}](lectures/{m['slug']}.qmd){{.module-card-title}}",
            "",
            m["summary"],
            "",
            "::: {.module-card-actions}",
            f"[Read the lecture](lectures/{m['slug']}.qmd){{.btn-quiet}} {colab_button(v, m)} "
            + chips(m["stack"]),
            ":::",
            ":::",
            ":::",
        ]
    out.append(":::")
    return "\n".join(out)


def module_block(v: dict, key: str, m: dict) -> str:
    """The header of a lecture page. Links are project-absolute: the including page
    sits in lectures/."""
    day = next(d for d in v["days"].values() if d["n"] == m["day"])
    lines = [
        "::: {.module-header}",
        "::: {.module-meta}",
        f"[Day {m['day']} · {day['short']}](/day-{m['day']}.qmd){{.module-day}} "
        f"[Module {m['n']}]{{.module-num}} [{timing(v, key, m)}]{{.module-time}}",
        ":::",
        "",
        "::: {.module-summary}",
        m["summary"],
        ":::",
        "",
        "::: {.module-actions}",
        f"{colab_button(v, m, 'Open the lab in Colab')} {chips(m['stack'])}",
        ":::",
        ":::",
        "",
        "::: {.objectives}",
        "## Learning objectives",
        "",
        "By the end of this module you can:",
        "",
    ]
    lines += [f"- {o}" for o in m["objectives"]]
    lines.append(":::")
    return "\n".join(lines)


def notebooks_index(v: dict) -> str:
    s = v["setup"]
    out = [
        "::: {.module-cards}",
        "::: {.module-card}",
        "::: {.module-card-time}",
        "Before Day 1",
        ":::",
        "",
        "::: {.module-card-body}",
        f"[Start here · {s['minutes']} minutes]{{.eyebrow}}",
        "",
        f"[{s['title']}]{{.module-card-title}}",
        "",
        s["summary"],
        "",
        "::: {.module-card-actions}",
        colab_button(v, {"slug": s["slug"]}),
        ":::",
        ":::",
        ":::",
        ":::",
    ]
    for d in days_in_order(v):
        labs = [m for _, m in day_modules(v, d) if has_notebook(m)]
        out += [
            "",
            f"## Day {d['n']} · {d['short']} {{#day-{d['n']}}}",
            "",
            "::: {.notebook-table}",
            "| # | Notebook | Lecture | Lab |",
            "|---|---|---|---|",
        ]
        for m in labs:
            out.append(
                f"| {m['n']} | **{m['title']}** [{m['summary']}]{{.notebook-summary}} "
                f"| [Lecture {m['n']}](lectures/{m['slug']}.qmd) | {colab_button(v, m)} |"
            )
        out.append(":::")
    return "\n".join(out)


def sidebar_yaml(v: dict) -> str:
    """website.sidebar for _quarto.yml (read through metadata-files): the modules
    grouped by day. Quarto shows it on the pages it lists and derives the
    previous/next links at the foot of each lecture from the same order."""
    sections = []
    for d in days_in_order(v):
        sections.append(
            {
                "section": f"Day {d['n']} · {d['short']}",
                "contents": [
                    {"href": f"lectures/{m['slug']}.qmd", "text": f"{m['n']} · {m['title']}"}
                    for _, m in day_modules(v, d)
                ],
            }
        )
    sidebar = {"id": "modules", "title": "Modules", "style": "floating", "contents": sections}
    return yaml.safe_dump(
        {"website": {"sidebar": [sidebar]}}, sort_keys=False, allow_unicode=True, width=1000
    )


def readiness_status(v: dict, records: list[dict]) -> str:
    """One paragraph: is the workshop ready to teach, and what has run where."""
    s = readiness.summary(v, records)
    ci = [r for r in records if r["env"] == "gha-ubuntu" and r["status"] == "pass"]
    ci_date = max((r["date"] for r in ci), default=None)
    ci_doubles = len({r["notebook"] for r in ci if r["path"] == "offline"})
    ready = s["teaching"] == s["labs"] and s["items_open"] == 0
    verdict = "ready to teach" if ready else "not yet ready to teach"
    parts = [
        f"**As of {s['as_of']}: {verdict}.**",
        f"{s['teaching']} of {s['labs']} labs have run end to end on Google Colab,"
        " the runtime they are designed for.",
        f"{s['real']} have run end to end on their real path on another machine,"
        f" and {s['real_partial_only']} more in part.",
    ]
    if ci_date:
        parts.append(
            f"In CI on {ci_date}, {len({r['notebook'] for r in ci})} of {s['notebooks']}"
            f" notebooks passed on a GitHub CPU runner; {ci_doubles} of those runs used"
            " test doubles, which check that the code runs, not what the models do."
        )
    parts.append(f"{s['items_open']} of {s['items']} pieces of blocking work are open.")
    return " ".join(parts)


def readiness_summary(v: dict, records: list[dict]) -> str:
    return (
        readiness_status(v, records)
        + " [What has run, where, and what is missing](/readiness.qmd)."
    )


def _accounts(r: dict) -> str:
    text = ", ".join(r["accounts"])
    if r.get("optional_accounts"):
        text += f"; optional: {', '.join(r['optional_accounts'])}"
    return (
        f"{text}. {r['cost'][0].upper()}{r['cost'][1:]}" if r["cost"] != "free" else f"{text}. Free"
    )


def readiness_table(v: dict, records: list[dict]) -> str:
    """The full readiness page: one row per module, the open work, and a legend."""
    R = v["readiness"]
    envs = R["envs"]
    rows = [
        "| Module | Content | Designed for | Evidence | Without API keys | Accounts and cost |",
        "|---|---|---|---|---|---|",
    ]
    for _, m in modules_in_order(v):
        r = m["readiness"]
        content = f"Lecture {r['lecture']}" + (f" · lab {r['lab']}" if r["lab"] != "none" else "")
        planned = f"{envs[r['runtime']]['name']} · estimate {r['estimate_minutes']} min"
        if has_notebook(m):
            e = readiness.evidence(v, m["slug"], records)
            lines = [
                "**On Colab:** "
                + (readiness.describe(v, e["teaching"]) if e["teaching"] else "not run"),
                "**Real path:** "
                + (
                    readiness.describe(v, e["real"])
                    if e["real"]
                    else readiness.describe(v, e["real_partial"])
                    if e["real_partial"]
                    else "not run"
                ),
                "**Code check:** "
                + (
                    readiness.describe(v, e["code"])
                    if e["code"]
                    else "no test doubles: CI runs the real path"
                    if e["real"] and e["real"]["env"] == "gha-ubuntu"
                    else "—"
                ),
            ]
            evidence = "<br>".join(lines)
        else:
            evidence = "No notebook. Not yet run on a fresh laptop"
        kind = r["fallback"]["kind"]
        fallback = {"none": "One path", "open-model": "Open model", "toy": "Toy model"}[kind]
        rows.append(
            f"| [{m['n']} · {m['title']}](/lectures/{m['slug']}.qmd) | {content} | {planned} "
            f"| {evidence} | **{fallback}.** {r['fallback']['note']} | {_accounts(r)} |"
        )
    out = [
        readiness_status(v, records),
        "",
        "::: {.column-page .table-wide .readiness-table}",
        "\n".join(rows),
        ":::",
        "",
    ]

    out += ["## Blocking work {#open-work}", ""]
    for item in readiness.items(v):
        mods = ", ".join(str(n) for n in item["modules"])
        word = "module" if len(item["modules"]) == 1 else "modules"
        mark = "Done" if item["closed"] else "Open"
        out.append(f"- **{mark}:** {item['title']} ({word} {mods}; {item['why']})")
    out.append("")

    gaps = [
        (m, m["readiness"]["gaps"]) for _, m in modules_in_order(v) if m["readiness"].get("gaps")
    ]
    if gaps:
        out += ["## Known gaps by module {#gaps}", ""]
        out += [f"- **{m['n']} · {m['title']}:** {gap}." for m, gap in gaps]
        out.append("")

    out += ["## How to read this page {#legend}", ""]
    out.append(
        "**Evidence.** Each line is the newest passing run of that kind, from the run records in"
        " [`runs/`]({{< var repo.url >}}/tree/main/runs). *On Colab* means the whole notebook"
        " ran on its real path on a Colab runtime and a tool recorded it. *Real path* means"
        " the whole notebook ran without test doubles on some machine; a laptop's or a CPU"
        " runner's time does not predict a T4's. *Code check* means CI ran the notebook with"
        " test doubles: it shows that the code runs, not what a model does. An estimate is a"
        " planning figure from the lab's brief, not a measurement."
    )
    out.append("")
    out.append("**Paths.**")
    out.append("")
    out += [f"- `{k}`: {text}." for k, text in R["paths"].items()]
    out.append("")
    out.append("**Without API keys.**")
    out.append("")
    labels = {"none": "One path", "open-model": "Open model", "toy": "Toy model"}
    out += [f"- *{labels[k]}*: {text}." for k, text in R["fallback_kinds"].items()]
    return "\n".join(out)


def readme_status(v: dict, records: list[dict]) -> str:
    site = v["repo"]["site_url"]
    return f"> {readiness_status(v, records)} See the [readiness page]({site}/readiness.html)."


def readme_table(v: dict) -> str:
    site = v["repo"]["site_url"]
    rows = ["| # | Day | Module | Lab |", "|---|---|---|---|"]
    for _, m in modules_in_order(v):
        rows.append(
            f"| {m['n']} | {m['day']} | [{m['title']}]({site}/lectures/{m['slug']}.html) "
            f"| {lab_cell(v, m)} |"
        )
    return "\n".join(rows)


def replace_region(path: Path, name: str, body: str) -> None:
    begin, end = f"<!-- BEGIN {name} -->", f"<!-- END {name} -->"
    text = path.read_text(encoding="utf-8")
    if begin not in text or end not in text:
        raise SystemExit(f"{path.name}: missing {begin} / {end} markers")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    path.write_text(f"{head}{begin}\n{body.rstrip()}\n{end}{tail}", encoding="utf-8")


LECTURE_STUB = """---
title: "{{{{< var modules.{key}.title >}}}}"
---

{{{{< include /_includes/module-{n:02d}.md >}}}}

::: {{.callout-note appearance="simple"}}
This lecture has not been drafted yet.
:::
"""


def scaffold_lectures(v: dict) -> None:
    for key, m in modules_in_order(v):
        page = ROOT / "lectures" / f"{m['slug']}.qmd"
        if not page.exists():
            page.parent.mkdir(exist_ok=True)
            page.write_text(LECTURE_STUB.format(key=key, n=m["n"]), encoding="utf-8")


def main() -> None:
    v = load_variables()
    write(INCLUDES / "facts.md", facts_strip(v))
    write(INCLUDES / "days.md", days_cards(v))
    write(INCLUDES / "path.md", path_steps(v))
    write(INCLUDES / "schedule.md", schedule_table(v))
    for d in days_in_order(v):
        write(INCLUDES / f"day-{d['n']}.md", day_cards(v, d))
    for key, m in modules_in_order(v):
        write(INCLUDES / f"module-{m['n']:02d}.md", module_block(v, key, m))
    write(INCLUDES / "notebooks.md", notebooks_index(v))
    records = run_records.load_all()
    write(INCLUDES / "readiness-summary.md", readiness_summary(v, records))
    write(INCLUDES / "readiness.md", readiness_table(v, records))
    sidebar = INCLUDES / "sidebar.yml"
    sidebar.write_text(f"{YAML_NOTICE}\n{sidebar_yaml(v)}", encoding="utf-8")
    replace_region(ROOT / "README.md", "status", readme_status(v, records))
    replace_region(ROOT / "README.md", "modules", readme_table(v))
    scaffold_lectures(v)


if __name__ == "__main__":
    main()
