"""Write the generated Markdown from _variables.yml.

Outputs (all overwritten on every run, never edited by hand):
  _includes/days.md          the four days at a glance
  _includes/schedule.md      the timetable
  _includes/day-N.md         the module table for one day
  _includes/module-NN.md     the header block of one lecture page
  _includes/notebooks.md     the notebook index with Colab badges
  README.md                  the region between the BEGIN/END modules markers

It also creates a stub lecture page for any module that has none. Existing
lecture pages are never touched.

Run:  uv run --group site python scripts/gen_tables.py
"""

from __future__ import annotations

from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
INCLUDES = ROOT / "_includes"
NOTICE = "<!-- GENERATED by scripts/gen_tables.py from _variables.yml. Do not edit by hand. -->"
BADGE = "https://colab.research.google.com/assets/colab-badge.svg"


def load_variables() -> dict:
    return yaml.safe_load((ROOT / "_variables.yml").read_text(encoding="utf-8"))


def modules_in_order(v: dict) -> list[tuple[str, dict]]:
    return sorted(v["modules"].items(), key=lambda kv: kv[1]["n"])


def days_in_order(v: dict) -> list[dict]:
    return sorted(v["days"].values(), key=lambda d: d["n"])


def notebook_exists(slug: str) -> bool:
    return (ROOT / "notebooks" / f"{slug}.ipynb").exists()


def colab_badge(v: dict, slug: str) -> str:
    """A Colab badge if the notebook exists, otherwise a plain note."""
    if not notebook_exists(slug):
        return "In preparation"
    return f"[![Open in Colab]({BADGE})]({v['repo']['colab_base']}/{slug}.ipynb)"


def slot_parts(slot) -> tuple[str, str | None]:
    """A day slot is a module key, or {module, label} to override the label."""
    if isinstance(slot, dict):
        return slot["module"], slot.get("label")
    return slot, None


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(f"{NOTICE}\n\n{body.rstrip()}\n", encoding="utf-8")


def days_table(v: dict) -> str:
    rows = ["| Day | Theme | Question it answers |", "|---|---|---|"]
    for d in days_in_order(v):
        rows.append(f"| [Day {d['n']}](day-{d['n']}.qmd) | {d['title']} | {d['question']} |")
    return "\n".join(rows)


def schedule_table(v: dict) -> str:
    days = days_in_order(v)
    head = "| Time | " + " | ".join(f"Day {d['n']}: {d['short']}" for d in days) + " |"
    rows = [head, "|---|" + "---|" * len(days)]
    module_index = 0
    for slot in v["schedule"]["slots"]:
        cells = []
        for d in days:
            if slot["kind"] == "opening":
                cells.append(d["opening"])
            elif slot["kind"] == "break":
                cells.append(slot["label"])
            else:
                key, label = slot_parts(d["slots"][module_index])
                m = v["modules"][key]
                text = label or m["title"]
                cells.append(f"[{m['n']} · {text}](lectures/{m['slug']}.qmd)")
        if slot["kind"] == "module":
            module_index += 1
        rows.append(f"| {slot['start']}–{slot['end']} | " + " | ".join(cells) + " |")
    return "\n".join(rows)


def day_table(v: dict, day: dict) -> str:
    rows = ["| # | Module | What you will do | Lab |", "|---|---|---|---|"]
    seen = set()
    for slot in day["slots"]:
        key, _ = slot_parts(slot)
        if key in seen:
            continue
        seen.add(key)
        m = v["modules"][key]
        rows.append(
            f"| {m['n']} | [{m['title']}](lectures/{m['slug']}.qmd) "
            f"| {m['summary']} | {colab_badge(v, m['slug'])} |"
        )
    return "\n".join(rows)


def module_block(v: dict, m: dict) -> str:
    w = v["workshop"]
    if m["minutes"] == w["lecture_minutes"] + w["lab_minutes"]:
        timing = f"{m['minutes']} minutes ({w['lecture_minutes']} lecture, {w['lab_minutes']} lab)"
    else:
        timing = f"{m['minutes']} minutes"
    lines = [
        f"**Day {m['day']} · Module {m['n']} · {timing}** · {', '.join(m['stack'])}",
        "",
        m["summary"],
        "",
        "**Lab:** " + colab_badge(v, m["slug"]),
        "",
        "## Learning objectives",
        "",
        "By the end of this module you can:",
        "",
    ]
    lines += [f"- {o}" for o in m["objectives"]]
    return "\n".join(lines)


def notebooks_table(v: dict) -> str:
    rows = ["| # | Notebook | Day | Open |", "|---|---|---|---|"]
    s = v["setup"]
    rows.append(f"| 0 | {s['title']} | Before Day 1 | {colab_badge(v, s['slug'])} |")
    for _, m in modules_in_order(v):
        rows.append(
            f"| {m['n']} | [{m['title']}](lectures/{m['slug']}.qmd) "
            f"| {m['day']} | {colab_badge(v, m['slug'])} |"
        )
    return "\n".join(rows)


def readme_table(v: dict) -> str:
    site = v["repo"]["site_url"]
    rows = ["| # | Day | Module | Lab |", "|---|---|---|---|"]
    for _, m in modules_in_order(v):
        rows.append(
            f"| {m['n']} | {m['day']} | [{m['title']}]({site}/lectures/{m['slug']}.html) "
            f"| {colab_badge(v, m['slug'])} |"
        )
    return "\n".join(rows)


def replace_region(path: Path, name: str, body: str) -> None:
    begin, end = f"<!-- BEGIN {name} -->", f"<!-- END {name} -->"
    text = path.read_text(encoding="utf-8")
    if begin not in text or end not in text:
        raise SystemExit(f"{path.name}: missing {begin} / {end} markers")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    path.write_text(f"{head}{begin}\n{body.rstrip()}\n{end}{tail}", encoding="utf-8")


LECTURE_STUB = """---
title: "{{{{< var modules.{key}.title >}}}}"
---

{{{{< include /_includes/module-{n:02d}.md >}}}}

::: {{.callout-note appearance="simple"}}
This lecture has not been drafted yet.
:::
"""


def scaffold_lectures(v: dict) -> None:
    for key, m in modules_in_order(v):
        page = ROOT / "lectures" / f"{m['slug']}.qmd"
        if not page.exists():
            page.parent.mkdir(exist_ok=True)
            page.write_text(LECTURE_STUB.format(key=key, n=m["n"]), encoding="utf-8")


def main() -> None:
    v = load_variables()
    write(INCLUDES / "days.md", days_table(v))
    write(INCLUDES / "schedule.md", schedule_table(v))
    for d in days_in_order(v):
        write(INCLUDES / f"day-{d['n']}.md", day_table(v, d))
    for _, m in modules_in_order(v):
        write(INCLUDES / f"module-{m['n']:02d}.md", module_block(v, m))
    write(INCLUDES / "notebooks.md", notebooks_table(v))
    replace_region(ROOT / "README.md", "modules", readme_table(v))
    scaffold_lectures(v)


if __name__ == "__main__":
    main()
